docker_username: ds40bamo

deploy:
  host: tldr.demo.webis.de
  resources:
    requests:
      cpu: "500m"
    limits:
      cpu: "4000m"

extern_environment:
  THREADS: 4
  BATCH_SIZE: 32
  CACHE_SIZE: 1000

metrics:
  - ./debug_plugin
  - ./metrics/bartscore
  - ./metrics/bertscore
  - ./metrics/bleu
  - ./metrics/bleurt
  - ./metrics/cider
  - ./metrics/spacy_similarity
  - ./metrics/greedy_matching
  - ./metrics/meteor
  - ./metrics/moverscore
  - source: ./metrics/rouge
    environment:
      model: "1"
  - source: ./metrics/rouge
    environment:
      model: "2"
  - source: ./metrics/rouge
    environment:
      model: "l"
  - ./metrics/sbert

summarizers:
  - ./debug_plugin
  # - ./summarizers/rag
  # - source: ./summarizers/rag
  #   environment:
  #     model: MaskEnt #TODO what should be the env?

